org.gradle.jvmargs=-Xmx2G -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

mod_id=chatcompanion
mod_name=Chat Companion
mod_version=0.1.0-alpha3
mod_license=All Rights Reserved
minecraft_version=1.21.1
neo_version=21.1.248
fabric_loader_version=0.19.5
fabric_api_version=0.116.17+1.21.1
gson_version=2.10.1
junit_version=5.11.4
