plugins {
    id 'net.neoforged.moddev'
}

base.archivesName = "chat-companion-neoforge-${minecraft_version}"

neoForge {
    version = neo_version

    runs {
        client { client() }
        server {
            server()
            programArgument '--nogui'
        }
        gameTestServer {
            type = 'gameTestServer'
            systemProperty 'neoforge.enabledGameTestNamespaces', mod_id
        }
    }

    mods {
        chatcompanion {
            sourceSet sourceSets.main
            sourceSet project(':core').sourceSets.main
            sourceSet project(':minecraft-common').sourceSets.main
        }
    }
}

dependencies {
    implementation project(':core')
    implementation project(':minecraft-common')
}

processResources {
    inputs.properties(mod_id: mod_id, mod_name: mod_name, mod_version: mod_version,
            mod_license: mod_license, neo_version: neo_version)
    filesMatching('META-INF/neoforge.mods.toml') {
        expand(mod_id: mod_id, mod_name: mod_name, mod_version: mod_version,
                mod_license: mod_license, neo_version: neo_version)
    }
}

tasks.named('jar') {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    from project(':core').sourceSets.main.output
    from project(':minecraft-common').sourceSets.main.output
}
